"""
Seed data for 25 simulated stocks across 5 sectors.
Uses realistic-looking price ranges and volatility values.
"""

STOCKS = [
    # --- TECHNOLOGY ---
    {
        "symbol": "NVEX",
        "name": "Novex Semiconductors",
        "sector": "Technology",
        "current_price": 487.32,
        "market_cap": 1_200_000_000,
        "volatility": 0.025,
        "drift": 0.0002,
    },
    {
        "symbol": "CLUD",
        "name": "CloudMatrix Corp",
        "sector": "Technology",
        "current_price": 231.50,
        "market_cap": 850_000_000,
        "volatility": 0.022,
        "drift": 0.00015,
    },
    {
        "symbol": "AIQR",
        "name": "AiQuant Research",
        "sector": "Technology",
        "current_price": 156.80,
        "market_cap": 620_000_000,
        "volatility": 0.030,
        "drift": 0.0003,
    },
    {
        "symbol": "CYBX",
        "name": "CyberXcel Inc",
        "sector": "Technology",
        "current_price": 89.45,
        "market_cap": 340_000_000,
        "volatility": 0.028,
        "drift": 0.0001,
    },
    {
        "symbol": "QNTM",
        "name": "Quantum Dynamics",
        "sector": "Technology",
        "current_price": 312.10,
        "market_cap": 970_000_000,
        "volatility": 0.027,
        "drift": 0.00018,
    },
    # --- FINANCE ---
    {
        "symbol": "VLTX",
        "name": "Vaultex Financial",
        "sector": "Finance",
        "current_price": 145.60,
        "market_cap": 780_000_000,
        "volatility": 0.018,
        "drift": 0.00008,
    },
    {
        "symbol": "APXB",
        "name": "Apex Banking Corp",
        "sector": "Finance",
        "current_price": 67.30,
        "market_cap": 450_000_000,
        "volatility": 0.015,
        "drift": 0.00005,
    },
    {
        "symbol": "MNTR",
        "name": "Mentor Capital",
        "sector": "Finance",
        "current_price": 203.75,
        "market_cap": 920_000_000,
        "volatility": 0.017,
        "drift": 0.00010,
    },
    {
        "symbol": "STLR",
        "name": "Stellar Insurance",
        "sector": "Finance",
        "current_price": 52.20,
        "market_cap": 280_000_000,
        "volatility": 0.016,
        "drift": 0.00006,
    },
    {
        "symbol": "TRDE",
        "name": "TradEdge Securities",
        "sector": "Finance",
        "current_price": 118.90,
        "market_cap": 560_000_000,
        "volatility": 0.019,
        "drift": 0.00009,
    },
    # --- ENERGY ---
    {
        "symbol": "SOLX",
        "name": "SolarXtreme Energy",
        "sector": "Energy",
        "current_price": 78.45,
        "market_cap": 390_000_000,
        "volatility": 0.023,
        "drift": 0.00012,
    },
    {
        "symbol": "FUSN",
        "name": "Fusion Power Corp",
        "sector": "Energy",
        "current_price": 44.80,
        "market_cap": 210_000_000,
        "volatility": 0.031,
        "drift": 0.00020,
    },
    {
        "symbol": "GRNE",
        "name": "GreenEarth Resources",
        "sector": "Energy",
        "current_price": 162.30,
        "market_cap": 640_000_000,
        "volatility": 0.020,
        "drift": 0.00011,
    },
    {
        "symbol": "HYDR",
        "name": "HydroGen Systems",
        "sector": "Energy",
        "current_price": 93.60,
        "market_cap": 430_000_000,
        "volatility": 0.026,
        "drift": 0.00014,
    },
    {
        "symbol": "WINX",
        "name": "WindXcel Industries",
        "sector": "Energy",
        "current_price": 35.25,
        "market_cap": 160_000_000,
        "volatility": 0.024,
        "drift": 0.00013,
    },
    # --- HEALTHCARE ---
    {
        "symbol": "BION",
        "name": "BioNex Pharmaceuticals",
        "sector": "Healthcare",
        "current_price": 267.80,
        "market_cap": 1_050_000_000,
        "volatility": 0.029,
        "drift": 0.00016,
    },
    {
        "symbol": "GENX",
        "name": "GenXcel Biotech",
        "sector": "Healthcare",
        "current_price": 134.50,
        "market_cap": 510_000_000,
        "volatility": 0.033,
        "drift": 0.00022,
    },
    {
        "symbol": "MEDI",
        "name": "MediCore Systems",
        "sector": "Healthcare",
        "current_price": 88.20,
        "market_cap": 360_000_000,
        "volatility": 0.021,
        "drift": 0.00009,
    },
    {
        "symbol": "NROX",
        "name": "NeuroXcel Labs",
        "sector": "Healthcare",
        "current_price": 345.60,
        "market_cap": 1_380_000_000,
        "volatility": 0.032,
        "drift": 0.00025,
    },
    {
        "symbol": "VITA",
        "name": "VitaGen Therapeutics",
        "sector": "Healthcare",
        "current_price": 57.90,
        "market_cap": 230_000_000,
        "volatility": 0.028,
        "drift": 0.00015,
    },
    # --- CONSUMER ---
    {
        "symbol": "LUXE",
        "name": "LuxEdge Retail",
        "sector": "Consumer",
        "current_price": 176.40,
        "market_cap": 710_000_000,
        "volatility": 0.019,
        "drift": 0.00007,
    },
    {
        "symbol": "FSTR",
        "name": "FastRoute Logistics",
        "sector": "Consumer",
        "current_price": 64.70,
        "market_cap": 290_000_000,
        "volatility": 0.022,
        "drift": 0.00008,
    },
    {
        "symbol": "METV",
        "name": "MetaVerse Entertainment",
        "sector": "Consumer",
        "current_price": 212.30,
        "market_cap": 830_000_000,
        "volatility": 0.035,
        "drift": 0.00030,
    },
    {
        "symbol": "NTRX",
        "name": "NutriX Foods",
        "sector": "Consumer",
        "current_price": 41.60,
        "market_cap": 185_000_000,
        "volatility": 0.016,
        "drift": 0.00005,
    },
    {
        "symbol": "ECOM",
        "name": "eComGlobal Inc",
        "sector": "Consumer",
        "current_price": 389.90,
        "market_cap": 1_550_000_000,
        "volatility": 0.024,
        "drift": 0.00020,
    },
]
